### ISSUE TITLE
Throws error on single-spa-layout@1.0.0-beta.6 package

### ISSUE THREAD

**Issue by joeldenning** [ljharb/list-exports#2] opened 2020-08-18 19:37 UTC
Using list-exports@1.0.1 and ls-exports@1.0.2, I get an error when running `ls-exports package single-spa-layout@1.0.0-beta.6`.

```sh
Top-level files/directories that contribute specifiers:
TypeError: Cannot read property 'dist/' of undefined
    at /Users/joeldenning/code/single-spa-layout/node_modules/ls-exports/exportsTable.js:88:18
    at Array.map (<anonymous>)
    at exportsTable (/Users/joeldenning/code/single-spa-layout/node_modules/ls-exports/exportsTable.js:86:4)
```

Here is the package.json for single-spa-layout: https://unpkg.com/browse/single-spa-layout@1.0.0-beta.6/package.json

It uses `"exports"` and `"main"`. I did a bit of debugging and discovered that in list-exports, the `legacyTree` has a `single-spa-layout` key but that `tree` does not. Since `tree` is what is returned, the returned tree is just an empty object which is why `x.tree[x.name]` is undefined.

It is quite possible that single-spa-layout@beta has an invalid package.json, in which case I would expect list-exports to print a descriptive error message instead of throwing this error. From my testing, the package.json seems to be valid - I am able to import it with Node 13.14.0 via an (uncompiled) ESM `import` statement.

**Comment by ljharb** [comment] 2020-08-18 20:38
Thanks, easily reproduced. Interestingly it works fine with `--json`. I should have a fix for this soon.

**Closed** 2020-08-18 21:49 UTC

**Comment by ljharb** [comment] 2020-08-18 21:59
`list-exports` v1.0.2 is published.

**Comment by joeldenning** [comment] 2020-08-18 22:15
Confirmed that it's working. Thanks!

**Comment by ljharb** [comment] 2020-09-25 21:02
@joeldenning See #4 - it seems like perhaps this package.json is indeed invalid. When you claim that you're able to import it in node v13.14, note that for "exports" to work, the package MUST be inside a `node_modules` folder. When I test this in node v13.14 (and v14 latest), it fails to be required or exported.

**Comment by joeldenning** [comment] 2020-09-26 15:42
I updated the package.json for single-spa-layout in later versions - I think it's now valid. When testing previously, I was using npm link and indeed saw things working. However, I had made a lot of changes to a lot of code at that point, so it's quite possible that I had fixed the package.json exports. Since i was not confident that my testing was covering a 100% normal use, I said in the original issue that "it is quite possible that single-spa-layout@beta has an invalid package.json"

**Comment by ljharb** [comment] 2020-09-26 19:15
Try installing it without linking and see if it works?

**Comment by joeldenning** [comment] 2020-09-27 20:25
Yes the latest version is working for me. See https://github.com/single-spa/single-spa-layout/commit/df88fb80ddcb1cda8b091b09bb3977cf4c68eea9

**Comment by ljharb** [comment] 2020-09-28 04:51
Thanks, your [exports field](https://github.com/single-spa/single-spa-layout/blob/main/package.json#L8-L21) looks like something we should already support then :-)
